fix: ident and order

diff --git a/.github/workflows/check-docs-updates.yml b/.github/workflows/check-docs-updates.yml
--- a/.github/workflows/check-docs-updates.yml
+++ b/.github/workflows/check-docs-updates.yml
@@ -11,6 +11,15 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
+      - name: Check BZSt connection
+        run: |
+          curl -v -o /dev/null https://api.evatr.vies.bzst.de/api-docs 2>&1
+          if [ $? -ne 0 ]; then
+            echo "❌ Failed to connect to BZSt server"
+            exit 1
+          fi
+          echo "✅ Successfully connected to BZSt server"
+
       - name: Checkout code
         uses: actions/checkout@v6
 
@@ -34,15 +43,6 @@ jobs:
           key: docs-cache-v5-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             docs-cache-v5-
-
-              - name: Check BZSt API access
-                run: |
-                  curl -v -o /dev/null https://api.evatr.vies.bzst.de/api-docs 2>&1
-                  if [ $? -ne 0 ]; then
-                    echo "❌ Failed to connect to BZSt server"
-                    exit 1
-                  fi
-                  echo "✅ Successfully connected to BZSt server"
 
       - name: Download and check docs files
         id: check-changes
